### ISSUE TITLE
Avoid check for certificate changes every 5 seconds

### ISSUE THREAD

**Issue by git-developer** [jlesage/docker-avidemux#7]
I'm using the avidemux Docker image v1.3.0 / Docker 20.10.3 (build 48d30b5).

I observed that the PIDs for new processes are very large (>800.000) on my system. I installed `forkstat` and noticed that the avidemux docker image forks 26 processes in a 5 second interval for the following command: `sh ./certsmonitor`.

I don't need this feature. Is it required? Can I disable it somehow?

**Comment by jlesage** [comment]
I guess you have the `SECURE_CONNECTION` environment variable set to `1` ?  In this case, there a script that checks for changes in certificates to automatically reload relevant processes.

**Comment by jlesage** [comment]
Yes, I guess the check interval could be configured via an environment variable.

**Comment by git-developer** [comment]
I didn't find such a variable and solved the problem within my `docker-compose.yml`:
```yaml
    environment:
      - CERTSMONITOR_INTERVAL=86400
    command: [ "sh", "-c", "sed -i 's/sleep 5/sleep \"$${CERTSMONITOR_INTERVAL:-5}\"/' /etc/services.d/certsmonitor/run && exec /init" ]
```
